name: Build Maven Kotlin Project

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: false

jobs:
  # 1. Run Tests first to catch issues early
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.0

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Tests
        run: mvn -B test --file pom.xml

  # 2. Build and package the application only if tests pass
  build:
    needs: test  # This ensures build only runs if tests pass
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.0

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      # Using -DskipTests here speeds up this step since they already ran in the previous job
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml